server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:file:~/aplicacao;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
